# Welcome to **UTD**Quake
[![UTDQuake](https://img.shields.io/badge/UTD-Quake-black?labelColor=orange&style=flat)](https://utdquake.readthedocs.io/en/latest/index.html)
[![Hugging Face Dataset](https://img.shields.io/badge/HuggingFace-Dataset-yellow?style=flat&logo=huggingface&logoColor=black?style=social)](https://huggingface.co/datasets/ecastillot/UTDQuake)
[![PyPI](https://img.shields.io/pypi/v/utdquake?color=blue&label=PyPI&style=flat)](https://pypi.org/project/utdquake/)
[![GitHub](https://img.shields.io/badge/GitHub-UTDQuake-black?logo=github)](https://github.com/ecastillot/UTDQuake)
![GitHub stars](https://img.shields.io/github/stars/ecastillot/UTDQuake?style=social)

A global earthquake dataset constructed from high-quality source and receiver metadata, including associated seismic phase picks across diverse station geometries.

> **Note:** It does not include waveforms by the moment, however curated datasets of earthquake events and phase picks are essential for modern seismology, especially in the AI era. While waveform datasets have advanced earthquake detection, multistation picks provide complementary information crucial for phase association and earthquake location.

## Overview

- More than 360K earthquakes, 12M picks (5.1M P & 2.4 S picks), and data from about 50K stations worldwide.
- More than 80 networks over the world with diverse distribution in:
  - Station density, Station geometry, Earthquake Epicentral location, Earthquake Depth, Earthquake Azimuthal gap, Number of P and S picks, Medium properties (Vp/Vs)

## Content
This guide provides a basic overview of [`UTDQuake`](https://github.com/ecastillot/UTDQuake) and demonstrates how to access datasets, networks, events, and visualizations. You can also see the documentation here: [![Read the Docs](https://img.shields.io/readthedocs/utdquake?style=for-the-badge&style=flat)](https://utdquake.readthedocs.io/en/latest/index.html)

Sections in this notebook:

- 📦 **Installation**
- 📊 **Dataset**
- ⚡ **Quick Access**
    - 🛰️ **Network**
    - 🌎 **Events**
    - 🏢 **Stations**
    - 📡 **Picks**
    - 💾 **Banks**
- 🚀 **Next Steps**
- ✍️ **Authors**

## Installation

You can install `UTDQuake` directly from PyPI using pip. This will install the Python package and its dependencies.

In [6]:
!pip install utdquake

Requirement already satisfied: utdquake in /usr/local/lib/python3.12/dist-packages (0.1)
Requirement already satisfied: datasets in /usr/local/lib/python3.12/dist-packages (from utdquake) (4.0.0)
Requirement already satisfied: huggingface-hub in /usr/local/lib/python3.12/dist-packages (from utdquake) (0.36.0)
Requirement already satisfied: obspy in /usr/local/lib/python3.12/dist-packages (from utdquake) (1.4.2)
Requirement already satisfied: obsplus in /usr/local/lib/python3.12/dist-packages (from utdquake) (0.3.2)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from utdquake) (2.2.2)
Requirement already satisfied: pyarrow in /usr/local/lib/python3.12/dist-packages (from utdquake) (18.1.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from utdquake) (1.26.4)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (from utdquake) (3.10.0)
Requirement already satisfied: seaborn in /usr/local/lib/python3.12/dist-packages (from utdquake) (0.13.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from utdquake) (25.0)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from utdquake) (1.16.3)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets->utdquake) (3.20.3)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets->utdquake) (0.3.8)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets->utdquake) (2.32.4)
Requirement already satisfied: tqdm>=4.66.3 in /usr/local/lib/python3.12/dist-packages (from datasets->utdquake) (4.67.1)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets->utdquake) (3.6.0)
Requirement already satisfied: multiprocess<0.70.17 in /usr/local/lib/python3.12/dist-packages (from datasets->utdquake) (0.70.16)
Requirement already satisfied: fsspec<=2025.3.0,>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets->utdquake) (2025.3.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from datasets->utdquake) (6.0.3)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub->utdquake) (4.15.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub->utdquake) (1.2.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->utdquake) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib->utdquake) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->utdquake) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->utdquake) (1.4.9)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib->utdquake) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->utdquake) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib->utdquake) (2.9.0.post0)
Requirement already satisfied: progressbar2 in /usr/local/lib/python3.12/dist-packages (from obsplus->utdquake) (4.5.0)
Requirement already satisfied: pydantic<3.0,>=2.0 in /usr/local/lib/python3.12/dist-packages (from obsplus->utdquake) (2.12.3)
Requirement already satisfied: tables in /usr/local/lib/python3.12/dist-packages (from obsplus->utdquake) (3.10.2)
Requirement already satisfied: lxml in /usr/local/lib/python3.12/dist-packages (from obspy->utdquake) (6.0.2)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from obspy->utdquake) (75.2.0)
Requirement already satisfied: sqlalchemy<2 in /usr/local/lib/python3.12/dist-packages (from obspy->utdquake) (1.4.54)
Requirement already satisfied: decorator in /usr/local/lib/python3.12/dist-packages (from obspy->utdquake) (4.4.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->utdquake) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->utdquake) (2025.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets->utdquake) (3.13.3)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0,>=2.0->obsplus->utdquake) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0,>=2.0->obsplus->utdquake) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0,>=2.0->obsplus->utdquake) (0.4.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib->utdquake) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets->utdquake) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets->utdquake) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets->utdquake) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets->utdquake) (2026.1.4)
Requirement already satisfied: greenlet!=0.4.17 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy<2->obspy->utdquake) (3.3.1)
Requirement already satisfied: python-utils>=3.8.1 in /usr/local/lib/python3.12/dist-packages (from progressbar2->obsplus->utdquake) (3.9.1)
Requirement already satisfied: numexpr>=2.6.2 in /usr/local/lib/python3.12/dist-packages (from tables->obsplus->utdquake) (2.14.1)
Requirement already satisfied: py-cpuinfo in /usr/local/lib/python3.12/dist-packages (from tables->obsplus->utdquake) (9.0.0)
Requirement already satisfied: blosc2>=2.3.0 in /usr/local/lib/python3.12/dist-packages (from tables->obsplus->utdquake) (3.12.2)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets->utdquake) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets->utdquake) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets->utdquake) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets->utdquake) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets->utdquake) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets->utdquake) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets->utdquake) (1.22.0)
Requirement already satisfied: ndindex in /usr/local/lib/python3.12/dist-packages (from blosc2>=2.3.0->tables->obsplus->utdquake) (1.10.1)
Requirement already satisfied: msgpack in /usr/local/lib/python3.12/dist-packages (from blosc2>=2.3.0->tables->obsplus->utdquake) (1.1.2)
Requirement already satisfied: platformdirs in /usr/local/lib/python3.12/dist-packages (from blosc2>=2.3.0->tables->obsplus->utdquake) (4.5.1)

> **Note:** If you are using Google Colab, make sure to **restart the runtime** after installation.

# Dataset

The **UTDQuake Dataset** contains all the seismic data used in this project. You can explore its full structure and details here: [Dataset Structure](https://utdquake.readthedocs.io/en/latest/dataset.html).

To get started, first create an instance of the `Dataset` class:

In [5]:
import utdquake as utdq

# dataset overview
dataset = utdq.Dataset()
print(dataset)

UTDQuake(root=/root/.utdquake)

> **Note:** `UTDQuake` requires a dedicated directory (***root***) to store all downloaded data, including datasets, networks, stations, and events. **By default, this directory is created inside your home folder**. If you prefer to use a different location, you can specify a custom path using the UTDQUAKE_ROOT environment variable. This is explained in the [Configuration](https://utdquake.readthedocs.io/en/latest/installation.html#:~:text=import%20os%0Aos.environ%5B%22UTDQUAKE_ROOT%22%5D%20%3D%20%22/my/custom/path/for/utdquake_data%22) section.

You can access metadata for all available networks directly from the dataset.  
This returns a pandas `DataFrame` containing general information about each network.

In [2]:
# network level
network_data = dataset.networks
display(network_data)

,network,agency,continent,events,total_stations,confirmed_stations,calculated_stations,p_arrivals,s_arrivals,start_time,end_time,url,contributor,approx_lon_min,approx_lon_max,approx_lat_min,approx_lat_max,score,countries
0,AEIC,ISC,North America,5000,971,357,969,10160,3086,2018-07-20 05:09:59.400000,2024-12-28 14:29:57.590000,http://www.isc.ac.uk,AEIC,-180.000000,-120.98948,45.672160,74.165940,5.0,US: Alaska
1,AFAD,ISC,Middle East,5000,1253,304,1248,54551,44494,2024-09-22 01:52:19.000000,2024-12-31 06:47:02.000000,http://www.isc.ac.uk,AFAD,21.357400,49.09560,32.693200,44.570800,5.0,Middle East
2,ANF,ISC,North America,5000,384,0,384,46111,46584,2017-06-21 06:57:07.900000,2020-07-31 22:39:39.470000,http://www.isc.ac.uk,ANF,-180.000000,-90.71848,22.860080,83.609020,5.0,"US: Alaska, Eastern site"
3,ATH,ISC,Europe,4065,1729,896,1704,143665,76956,2024-04-19 00:05:16.500000,2024-06-30 23:59:32.600000,http://www.isc.ac.uk,ATH,17.052200,31.48480,32.388000,43.476000,5.0,Greece
4,AUST,ISC,Oceania,5000,3701,1822,3565,105015,26352,2018-04-26 08:21:02.380000,2025-07-31 23:24:56.360000,http://www.isc.ac.uk,AUST,-180.000000,180.00000,-84.175940,67.192340,5.0,Australia
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77,se,USGS,North America,2149,382,371,381,24797,11823,2012-09-30 19:46:01.990000,2025-07-27 04:16:14.290000,http://earthquake.usgs.gov,se,-90.829933,-74.26140,30.493160,42.088707,4.0,US: South East US
78,tx,USGS,North America,5000,323,304,323,110545,118704,2025-01-14 10:18:25.227326,2025-07-31 23:29:28.716900,http://earthquake.usgs.gov,tx,-106.592000,-92.91400,26.793800,37.036200,5.0,US: Texas
79,us,USGS,World,5000,3468,3345,3468,186648,12207,2025-06-22 23:34:27.533000,2025-07-31 23:59:53.390000,http://earthquake.usgs.gov,us,-180.000000,180.00000,-90.000000,90.000000,5.0,None
80,uu,USGS,North America,5000,260,260,260,63796,25250,2024-02-21 20:08:02.880000,2025-07-31 13:13:29.800000,http://earthquake.usgs.gov,uu,-115.360320,-107.64058,35.090467,46.783033,5.0,US: Utah
81,uw,USGS,North America,5000,849,846,849,80630,51838,2024-09-22 22:02:45.460000,2025-07-31 22:54:22.540000,http://earthquake.usgs.gov,uw,-130.732133,-114.16220,40.044800,51.042033,5.0,US: Washington and Oregon

In [17]:
dataset.description

Resolving data files:   0%|          | 0/82 [00:00<?, ?it/s]

Resolving data files:   0%|          | 0/82 [00:00<?, ?it/s]

Resolving data files:   0%|          | 0/82 [00:00<?, ?it/s]

Resolving data files:   0%|          | 0/82 [00:00<?, ?it/s]

{'events': 363967,
 'p_arrivals': 5132206,
 's_arrivals': 2440967,
 'total_stations': 57098,
 'confirmed_stations': 35166,
 'calculated_stations': 56484,
 'start_time': '2010-01-01 04:30:32.770000',
 'end_time': '2025-07-31 23:59:53.390000'}

# Quick Access

Easily retrieve detailed information for any specific network:

**Load a Network**  
You can load data for a specific network using its network code.  
Example: The Texas network corresponds to the code `"tx"`. This will return a `Network` class.

In [7]:
# load network
network = dataset.get_network(name="tx")
print(network)

Fetching 1 files:   0%|          | 0/1 [00:00<?, ?it/s]

Network(tx) | Events: 5000, Stations: 323

**Load Events**

In [8]:
# events
events = network.events
display(events)

Fetching 5 files:   0%|          | 0/5 [00:00<?, ?it/s]

bank/tx.zip:   0%|          | 0.00/59.5M [00:00<?, ?B/s]

picks/network=tx.parquet:   0%|          | 0.00/20.5M [00:00<?, ?B/s]

,network,time,latitude,longitude,depth,magnitude,azimuthal_gap,event_description,associated_phase_count,event_id,...,standard_error,used_phase_count,station_count,vertical_uncertainty,updated,author,agency_id,creation_time,version,path
0,tx,2025-07-31 06:35:19.245347,32.766,-100.687,11889.6,0.9,74.002802,Western Texas,14.0,smi:org.gfz-potsdam.de/geofon/tx2025oxvijj,...,NaN,11.0,9.0,1969.167896,2025-10-13 23:52:19,scevent@scdb.beg.utexas.edu,TX,2025-07-31 06:37:12.774330,<NA>,2025/07/31/tx2025oxvijj.xml
1,tx,2025-07-31 06:11:12.709449,32.118,-102.209,6372.1,0.9,66.648271,Western Texas,21.0,smi:org.gfz-potsdam.de/geofon/tx2025oxunpa,...,0.1,21.0,14.0,1748.014824,2025-10-13 23:52:19,scevent@scdb.beg.utexas.edu,TX,2025-07-31 06:13:04.209622,<NA>,2025/07/31/tx2025oxunpa.xml
2,tx,2025-07-31 13:47:21.273648,32.136,-101.073,5395.5,1.0,84.861942,Western Texas,13.0,smi:org.gfz-potsdam.de/geofon/tx2025oyjqqv,...,0.1,13.0,8.0,3317.435368,2025-10-13 23:52:19,scevent@scdb.beg.utexas.edu,TX,2025-07-31 23:11:43.118955,<NA>,2025/07/31/tx2025oyjqqv.xml
3,tx,2025-07-31 08:17:06.194621,32.101,-102.121,7251.0,0.8,71.896018,Western Texas,25.0,smi:org.gfz-potsdam.de/geofon/tx2025oxyrvt,...,0.2,25.0,15.0,791.440262,2025-10-13 23:52:19,scevent@scdb.beg.utexas.edu,TX,2025-07-31 08:17:18.095049,<NA>,2025/07/31/tx2025oxyrvt.xml
4,tx,2025-07-31 22:38:18.041990,32.120,-101.109,8886.7,1.2,77.650412,Western Texas,30.0,smi:org.gfz-potsdam.de/geofon/tx2025ozbgeo,...,0.2,23.0,18.0,1745.187011,2025-10-13 23:52:19,scevent@scdb.beg.utexas.edu,TX,2025-07-31 23:11:46.899452,<NA>,2025/07/31/tx2025ozbgeo.xml
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,tx,2025-01-14 12:57:41.536946,32.407,-102.072,6518.6,1.5,49.923575,Western Texas,56.0,smi:org.gfz-potsdam.de/geofon/texnet2025aytl,...,0.1,32.0,32.0,766.114040,2025-10-14 04:43:53,scevent@scdb.beg.utexas.edu,TX,2025-01-14 12:58:09.310891,<NA>,2025/01/14/texnet2025aytl.xml
4996,tx,2025-01-14 19:03:27.822860,31.880,-101.500,7983.4,1.5,61.317233,Western Texas,90.0,smi:org.gfz-potsdam.de/geofon/texnet2025azfi,...,0.1,23.0,52.0,2731.838724,2025-10-14 04:43:53,scevent@scdb.beg.utexas.edu,TX,2025-01-14 19:03:53.642592,<NA>,2025/01/14/texnet2025azfi.xml
4997,tx,2025-01-14 12:24:25.285708,31.730,-104.093,5625.6,1.6,29.056512,Western Texas,88.0,smi:org.gfz-potsdam.de/geofon/texnet2025aysg,...,0.1,33.0,59.0,651.628880,2025-10-14 04:43:53,scevent@scdb.beg.utexas.edu,TX,2025-01-14 12:24:34.741282,<NA>,2025/01/14/texnet2025aysg.xml
4998,tx,2025-01-14 12:19:34.106573,31.731,-104.092,6574.1,1.6,28.834083,Western Texas,90.0,smi:org.gfz-potsdam.de/geofon/texnet2025aysb,...,0.1,57.0,53.0,333.727805,2025-10-14 04:43:53,scevent@scdb.beg.utexas.edu,TX,2025-01-14 12:19:41.243527,<NA>,2025/01/14/texnet2025aysb.xml
4999,tx,2025-01-14 10:18:25.227326,31.962,-102.990,8618.2,1.8,35.177261,Western Texas,102.0,smi:org.gfz-potsdam.de/geofon/texnet2025aynz,...,0.1,23.0,60.0,4170.059130,2025-10-14 04:43:53,scevent@scdb.beg.utexas.edu,TX,2025-01-14 10:18:42.704152,<NA>,2025/01/14/texnet2025aynz.xml

**Load Stations**

In [10]:
# stations
stations = network.stations
display(stations)

,network,station,available,confirmed,confirmed_latitude,confirmed_longitude,confirmed_elevation,calculated,calculated_latitude,calculated_longitude,db_path,creation_time
0,tx,PB07,True,True,31.579350,-103.667930,856.0,True,31.579408,-103.667369,/groups/igonin/ecastillo/UTDQuake/test/1013202...,2025-10-13 23:52:22.424341
1,tx,PB54,True,True,31.894457,-103.416746,940.0,True,31.894411,-103.418798,/groups/igonin/ecastillo/UTDQuake/test/1013202...,2025-10-13 23:52:22.438644
2,tx,MB01,True,True,31.667734,-102.082910,859.0,True,31.668331,-102.082220,/groups/igonin/ecastillo/UTDQuake/test/1013202...,2025-10-13 23:52:22.448272
3,tx,NMP53,True,True,32.176260,-103.431176,1037.3,True,32.175801,-103.430422,/groups/igonin/ecastillo/UTDQuake/test/1013202...,2025-10-13 23:52:22.481513
4,tx,PB42,True,True,31.764578,-103.640224,830.0,True,31.764113,-103.639605,/groups/igonin/ecastillo/UTDQuake/test/1013202...,2025-10-13 23:52:22.485431
...,...,...,...,...,...,...,...,...,...,...,...,...
318,tx,NAS3,True,False,NaN,NaN,NaN,True,27.000300,-97.000114,/groups/igonin/ecastillo/UTDQuake/test/1013202...,2025-10-14 04:17:42.735628
319,tx,W35A,True,True,35.152740,-96.874530,322.0,True,35.153517,-96.865271,/groups/igonin/ecastillo/UTDQuake/test/1013202...,2025-10-14 04:35:42.004014
320,tx,CBKS,True,True,38.814000,-99.737400,677.0,True,38.807760,-99.734429,/groups/igonin/ecastillo/UTDQuake/test/1013202...,2025-10-14 04:35:41.988739
321,tx,AMTX,True,True,34.883700,-101.680800,1010.0,True,34.885246,-101.682321,/groups/igonin/ecastillo/UTDQuake/test/1013202...,2025-10-14 04:35:42.005141
322,tx,WMOK,True,True,34.737900,-98.780700,486.0,True,34.739743,-98.775743,/groups/igonin/ecastillo/UTDQuake/test/1013202...,2025-10-14 04:35:42.015782

**Load Picks**

In [11]:
picks = network.picks
display(picks)

,network,station,phase,travel_time,azimuth,distance,time,event_id,origin_time,resource_id_arrival,...,horizontal_slowness_weight,backazimuth_weight,earth_model_id,creation_time,author,agency_id,location,channel,origin_id,resource_id_pick
0,tx,ODSA,P,7.839736,67.052644,0.406315,2025-01-14 10:18:33.067062,smi:org.gfz-potsdam.de/geofon/texnet2025aynz,2025-01-14 10:18:25.227326,smi:org.gfz-potsdam.de/geofon/Pick/20250114133...,...,NaN,NaN,,NaT,,,00,HH2,smi:org.gfz-potsdam.de/geofon/NLL.202501151627...,smi:org.gfz-potsdam.de/geofon/Pick/20250114133...
1,tx,ODSA,S,13.634748,67.052644,0.406315,2025-01-14 10:18:38.862074,smi:org.gfz-potsdam.de/geofon/texnet2025aynz,2025-01-14 10:18:25.227326,smi:org.gfz-potsdam.de/geofon/Pick/20250114133...,...,NaN,NaN,,NaT,,,00,HH2,smi:org.gfz-potsdam.de/geofon/NLL.202501151627...,smi:org.gfz-potsdam.de/geofon/Pick/20250114133...
2,tx,PB06,S,13.616174,211.825792,0.369224,2025-01-14 10:18:38.843500,smi:org.gfz-potsdam.de/geofon/texnet2025aynz,2025-01-14 10:18:25.227326,smi:org.gfz-potsdam.de/geofon/Pick/20250114133...,...,NaN,NaN,,NaT,,,00,HH1,smi:org.gfz-potsdam.de/geofon/NLL.202501151627...,smi:org.gfz-potsdam.de/geofon/Pick/20250114133...
3,tx,PB19,P,13.634748,188.135781,0.663682,2025-01-14 10:18:38.862074,smi:org.gfz-potsdam.de/geofon/texnet2025aynz,2025-01-14 10:18:25.227326,smi:org.gfz-potsdam.de/geofon/Pick/20250114133...,...,NaN,NaN,,NaT,,,00,HHE,smi:org.gfz-potsdam.de/geofon/NLL.202501151627...,smi:org.gfz-potsdam.de/geofon/Pick/20250114133...
4,tx,PB19,S,23.404544,188.135781,0.663682,2025-01-14 10:18:48.631870,smi:org.gfz-potsdam.de/geofon/texnet2025aynz,2025-01-14 10:18:25.227326,smi:org.gfz-potsdam.de/geofon/Pick/20250114133...,...,NaN,NaN,,NaT,,,00,HHE,smi:org.gfz-potsdam.de/geofon/NLL.202501151627...,smi:org.gfz-potsdam.de/geofon/Pick/20250114133...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
229233,tx,EF61,S,20.663063,24.486194,0.518630,2025-07-31 23:29:49.379963,smi:org.gfz-potsdam.de/geofon/tx2025ozcyhu,2025-07-31 23:29:28.716900,smi:org.gfz-potsdam.de/geofon/Pick/20250801002...,...,NaN,NaN,,NaT,,,00,HHN,smi:org.gfz-potsdam.de/geofon/NLL.202508010029...,smi:org.gfz-potsdam.de/geofon/Pick/20250801002...
229234,tx,EF04,S,26.328699,34.588624,0.676505,2025-07-31 23:29:55.045599,smi:org.gfz-potsdam.de/geofon/tx2025ozcyhu,2025-07-31 23:29:28.716900,smi:org.gfz-potsdam.de/geofon/Pick/20250801002...,...,NaN,NaN,,NaT,,,00,HH1,smi:org.gfz-potsdam.de/geofon/NLL.202508010029...,smi:org.gfz-potsdam.de/geofon/Pick/20250801002...
229235,tx,EF04,P,15.926945,34.588624,0.676505,2025-07-31 23:29:44.643845,smi:org.gfz-potsdam.de/geofon/tx2025ozcyhu,2025-07-31 23:29:28.716900,smi:org.gfz-potsdam.de/geofon/Pick/20250801002...,...,NaN,NaN,,NaT,,,00,HHZ,smi:org.gfz-potsdam.de/geofon/NLL.202508010029...,smi:org.gfz-potsdam.de/geofon/Pick/20250801002...
229236,tx,HNDO,S,43.516333,313.757602,1.269581,2025-07-31 23:30:12.233233,smi:org.gfz-potsdam.de/geofon/tx2025ozcyhu,2025-07-31 23:29:28.716900,smi:org.gfz-potsdam.de/geofon/Pick/20250801002...,...,NaN,NaN,,NaT,,,00,CHE,smi:org.gfz-potsdam.de/geofon/NLL.202508010029...,smi:org.gfz-potsdam.de/geofon/Pick/20250801002...
229237,tx,HNDO,P,25.988272,313.757602,1.269581,2025-07-31 23:29:54.705172,smi:org.gfz-potsdam.de/geofon/tx2025ozcyhu,2025-07-31 23:29:28.716900,smi:org.gfz-potsdam.de/geofon/Pick/20250801002...,...,NaN,NaN,,NaT,,,00,CHZ,smi:org.gfz-potsdam.de/geofon/NLL.202508010029...,smi:org.gfz-potsdam.de/geofon/Pick/20250801002...

**Load Banks**

In [16]:
# get event bank
ebank = network.bank #
print("This is my Event Bank",ebank)

# Example: Filter by event_id
ev_ids = events["event_id"].iloc[:5].tolist()
cat = ebank.get_events(event_id=ev_ids)
print("First 5 earthquakes:", cat)

# Example 2: Other filter (check obsplus.EventBank for more details)
cat2 = ebank.get_events(minmagnitude=4.3)
print("Earthquakes above M4.3:",cat2)

This is my Event Bank EventBank(base_path=/root/.utdquake/bank/tx, index_path=/root/.utdquake/bank/tx/.index.db)
First 5 earthquakes: 5 Event(s) in Catalog:
2025-07-31T06:11:12.709449Z | +32.118, -102.209 | 0.9  ML | manual
2025-07-31T06:35:19.245347Z | +32.766, -100.687 | 0.9  ML | manual
2025-07-31T08:17:06.194621Z | +32.101, -102.121 | 0.8  ML | manual
2025-07-31T13:47:21.273648Z | +32.136, -101.073 | 1.0  ML | manual
2025-07-31T22:38:18.041990Z | +32.120, -101.109 | 1.2  ML | manual
Earthquakes above M4.3: 5 Event(s) in Catalog:
2025-05-04T01:47:05.553401Z | +31.647, -104.458 | 5.4  ML | manual
2025-02-28T19:33:24.297261Z | +32.370, -101.926 | 4.8  ML | manual
2025-02-18T12:16:28.873362Z | +31.711, -104.502 | 4.7  ML | manual
2025-02-15T05:23:21.429810Z | +31.661, -104.180 | 5.0  ML | manual
2025-01-30T03:26:36.879193Z | +29.058,  -97.846 | 4.6  ML | manual

# Author(s):

| Name | LinkedIn | Email |
|------|----------|-------|
| Emmanuel Castillo | <a href="https://www.linkedin.com/in/ecastillot/"><img src="https://img.shields.io/badge/LinkedIn-Follow-blue?logo=linkedin&logoColor=white&style=flat" height="15"></a> | <a href="mailto:castillo.280997@gmail.com"><img src="https://img.shields.io/badge/Email-Send-red?logo=gmail&logoColor=white&style=flat" height="15"></a> |
| Nadine Ushakov | <a href="https://www.linkedin.com/in/nadineushakov/"><img src="https://img.shields.io/badge/LinkedIn-Follow-blue?logo=linkedin&logoColor=white&style=flat" height="15"></a> | <a href="mailto:nadine.igonin@utdallas.edu"><img src="https://img.shields.io/badge/Email-Send-red?logo=gmail&logoColor=white&style=flat" height="15"></a> |
| Marine Denolle | <a href="https://www.linkedin.com/in/marine-denolle-b528144b/"><img src="https://img.shields.io/badge/LinkedIn-Follow-blue?logo=linkedin&logoColor=white&style=flat" height="15"></a> | <a href="mailto:mdenolle@uw.edu"><img src="https://img.shields.io/badge/Email-Send-red?logo=gmail&logoColor=white&style=flat" height="15"></a> |